---
title: "Enterprise Linux?"
date: 2025-09-20T16:31:33+02:00
draft: false
---

** Why?

Since it's release earlier this year, I have been using Red Hat Enterprise Linux 10 almost exclusively as my daily driver. Well, on my home computer, as I'm forced to use Windows for my day-job.
It might feel like a weird choice, given how there is Fedora Linux, which can be thought of as a more modern iteration of RHEL (given how it's the upstream project). The thing is, I've used Fedora before, but I could never become fully commited to it - sure, I love the near-stock Gnome experience, but that's not an exclusive to Fedora.
The reason why I've managed to stay on RHEL for longer than 2 months is exactly this: I kind of forgot about it. It's stable in a sense that I got bored running "dnf update" daily, just to see "Everything is up to date". In fact, I don't even remember when was the last time I opened the terminal to run an update.
There are other stable distributions - Debian, Suse, openSuse Leap, Rocky... - and yet I'm on a commercial offering. And there are two other reasons for that: me preparing for Red Hat Certifications for my job, and the fact that Red Hat gives out free licenses. If Suse would do the same, I probably would never have left it, but that's another story for another time.

** My desktop

I love Gnome, vanilla or heavily customized (looking at you, Ubuntu), matters little to me, as the workflow doesn't change much in either case.
Of course, I use /quite/ some extensions, but I don't agree with some others, who think Gnome should implement the most popular extensions as a base system offering. Part of the reason why I love Gnome is the fact that it's almost a blank sheet out of the box, that you can extend with... extensions. It's similar to how other DEs are praised for their customizability - you can do that too in Gnome, just in a different way.
The only thing I miss is the reimagined "Activities" button, that shows your workspaces, but I've enabled an extension that basically does the same.

** My workflow

I'm trying to use Emacs recently for as many tasks as I possibly can. Text editing, for one, but also for class notes, mastodon, wallabag, rss with elfeed... I've set it up to change to dark mode automatically.
It replaces many of my other, dedicated applications. I still use Firefox for web-browsing and Thunderbird for calendar and emails. I also use Planify for my to-do list, which is synced with Nextcloud to my phone, where I use tasks.org. Every once in a while I also use Joplin, which was my go-to notes application before swicthing over to Emacs Org-mode.

/To be continued.../
